package fabbroniko.gameobjects;

public enum Animations {
	PLAYER_WALK,
	PLAYER_JUMP,
	PLAYER_STILL,
	BLOCK_NORMAL,
	BLOCK_BREAKING,
	ENEMY_WALK,
	ENEMY_DEAD,
	INVISIBLEBLOCK_VISIBLE,
	INVISIBLEBLOCK_INVISIBLE,
	FALLING_BLOCK,
	CASTLE;
}
